# Generated by Django 3.0.6 on 2020-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.TextField(),
        ),
    ]
